version: '3.8'

services:
  postgres:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
